socialWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('socialWeb/', include('socialplatform.urls', namespace='SocialWeb')),
]

socialplatform/urls.py
from django.urls import path
from . import views

app_name = 'social'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.loginView, name='login'),
    path('signup/', views.SignupView, name='signup'),
    path('logout/', views.logoutView, name='logout'),

    path('groups_list/', views.groupList, name='group-list'),
    path('posts/<int:group_id>/', views.postList, name='post-list'),

    path('groups/', views.createGroup, name='create-group'),
    path('create-post/', views.createPost, name='create-post'),

    path('group/', views.join_group, name='group-join')
]

socialplatform/models.py
from django.db import models

# Create your models here.

class groupAdmin(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.username

class Group(models.Model):
    admin = models.ForeignKey(groupAdmin, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)    
    created = models.DateTimeField(auto_now_add=True)
    # members = models.PositiveIntegerField(unique=True, null=True)

    def __str__(self):
        return self.name
    
class GroupJoinedMembers(models.Model):
    group_name = models.ForeignKey(Group, on_delete=models.CASCADE)
    member = models.ForeignKey(groupAdmin, on_delete=models.CASCADE)

    def __str__(self):
        # print("Group Members: ", str(self.group_name))
        return str(self.group_name)

class Post(models.Model):
    group = models.ForeignKey(Group, related_name="posts", on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return f"{self.group} {self.message}"

socialplatform/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Group

class logInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignUpform(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']
    
    def clean_password2(self):
        pswd = self.cleaned_data
        if pswd['password1'] != pswd['password2']:
            raise ValidationError('Your password does not match, Re-enter your password again')
        
class GroupForm(forms.Form):
    name = forms.CharField(label="Group Name", initial="Group name...", max_length=100)
    description = forms.CharField(label="Group Description", initial="Description...", widget=forms.Textarea())


# get all groups 
def groupChoices():
   groups = Group.objects.all()
   return {f'{group}' : f'{group}' for group in groups}

class GroupPostForm(forms.Form):
    group = forms.ChoiceField(choices=groupChoices)
    message = forms.CharField(widget=forms.Textarea())

socialplatform/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.urls import reverse_lazy
from .models import Group, groupAdmin, Post, GroupJoinedMembers
from .forms import logInForm, SignUpform, GroupForm, GroupPostForm

def index(request):
    return render(request, 'socialplatform/index.html')

def loginView(request):
    if request.method == 'POST':
        form = logInForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user:
                login(request, user)

                # get created groups from all users
                Groups = Group.objects.annotate(no_of_posts=Count('posts'))

                # get group members 
                total_groups = Group.objects.all()

                group_members = [GroupJoinedMembers.objects.filter(group_name=g.id).count() for g in total_groups]

                # get groups for current user groups

                # filter group admin by email address and get id
                current_user = groupAdmin.objects.filter(email=user.email).values_list("id", flat=True)[0]
                print("current_user", current_user)
                # get groups for current logged-in user
                user_groups = Group.objects.filter(admin=current_user).annotate(no_of_posts = Count('posts'))

                # check if the current user joined the group
                chk = []
                for g in total_groups:
                    if (GroupJoinedMembers.objects.filter(group_name=g.id, member=current_user)):
                        chk.append(1)
                    else: 
                        chk.append(0)

                return render(request, 'socialplatform/register/login_success.html', {'user': user,
                                                                                      'Groups': Groups,
                                                                                      'user_groups': user_groups, 
                                                                                      "current_user": current_user,
                                                                                      'group_members': group_members,
                                                                                      'memberGroupJoined': chk})
            else:
                return render(request, 'socialplatform/index.html', {'msg': 'Invalid credentials'})
    else:
        form = logInForm()
    return render(request, 'socialplatform/register/login.html', {'form': form})

def logoutView(request):
    logout(request)
    return render(request, 'socialplatform/register/logout.html')

def SignupView(request):
    if request.method == 'POST':
        form = SignUpform(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = form.save(commit=False)
            user.set_password(cd['password1'])
            user.save()

            # 
            groupAdmin.objects.create(username=cd['username'], email=cd['email'])
            return redirect('social:login')
    else:
        form = SignUpform()
    return render(request, 'socialplatform/register/signup.html', {'form': form})

def groupList(request):
    Groups = Group.objects.all().annotate(no_of_posts = Count('posts'))
    
    return render(request, 'socialplatform/group/list_group.html', {"Groups": Groups})

@login_required
def createGroup(request):
    if request.method == 'POST':
        groupForm = GroupForm(request.POST)
        if groupForm.is_valid():
            cd = groupForm.cleaned_data
            if request.user.is_authenticated:
                # get current logged in user
                admin = request.user
                print(admin)
                print("SessionKey", request.session._session_key)
                # get user model from Admin model
                group_admin = groupAdmin.objects.get(username=admin)
                # create group for logged in user
                Group.objects.create(admin=group_admin, name=cd['name'], description=cd['description'])   

                all_post = Post.objects.filter(group=Group.objects.get(name=cd['name']))
            return render(request, 'socialplatform/group/group_created.html', {'groupName': cd['name'],
                                                                               'groupPosts': all_post})         
    else:
        groupForm = GroupForm()
    return render(request, 'socialplatform/group/group_form.html', {'form':groupForm})

def createPost(request):

    if request.method == 'POST':
        form = GroupPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            select_group = Group.objects.get(name=cd['group'])
            Post.objects.create(group=select_group , message=cd['message'])

            all_post = Post.objects.filter(group=select_group)
            return render(request, 'socialplatform/group/group_created.html', {'groupName': select_group,
                                                                               'groupPosts': all_post})         
    else:
        form = GroupPostForm()
    return render(request, 'socialplatform/post/create_post.html', {'form': form})
    
def postList(request, group_id):
    group = Group.objects.get(pk=group_id)
    all_posts = Post.objects.filter(group=group)

    group_members_count = GroupJoinedMembers.objects.filter(group_name=group_id).count()

    print("group_id: ", group_id)
    print(group_members_count)
    return render(request, 'socialplatform/post/post_display.html', {'Posts': all_posts,
                                                                     'Group': group,
                                                                     'group_members_count': group_members_count})


def join_group(request):
    group = request.POST.get('group_id')
    member = request.POST.get('user_id')
    print("Group ID: ", group)

    print("Current User: ", member)
    action = request.POST.get('action')

    print(action)
    if action == 'join Group':
        get_group = Group.objects.get(pk=group)
        get_member = groupAdmin.objects.get(pk=member)
        GroupJoinedMembers.objects.create(group_name=get_group, member=get_member)
        print("Group Joined")
    else:
        get_member = groupAdmin.objects.get(pk=member)
        GroupJoinedMembers.objects.filter(group_name=group, member=get_member).delete()
        print("Group Leaved")

    return JsonResponse({'status': 'ok'})

socialplatform/templates/socialplatform/index.html
{% load static %}
<html>
    <head>
        <meta charset='utf-8'>
        <title> Social Web </title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        {% comment %} Bootstrap Link {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

    </head>
    <body id="drop">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Social Site</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'social:index' %}">Home</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:create-post' %}"> Posts </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:create-group' %}"> Create Group </a>
                  </li>
                  <li class="nav-item">
                    <span> User: {{user}} </span>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:logout' %}">Log-out</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:group-list' %}"> Groups </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:login' %}">Log-in</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:signup' %}">Sign-up</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
       
        <div class="container mainCont">
            {% block content %}
                <h1> Welcome to star social </h1>
                <p>
                    <h3> The best community for all things <br> 
                         Login or Signup for free to get started!
                    </h3>
                </p>
                
            {% endblock %}
        </div>

        <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
        <script>
            const csrftoken = Cookies.get('csrftoken');
            console.log('Cookies: ', csrftoken);
            document.addEventListener("DOMContentLoaded", (event) => {
              {% block domready %}
              {% endblock %}
            });            
        </script>

        <script src="{% static 'js/waterDrop.js' %}"></script>
        <script src="{% static 'js/rain.js' %}"></script>
    </body>
</html>